### ISSUE TITLE
Bug on `Inverse Line Graph`

### ISSUE THREAD

**Issue by fsoupimenta** [GraphFilter/GraphFilter#395]
When performing the operation on a specific graph, the software crashed.

####  To reproduce the bug, simply follow these steps:

1. Open the `Graph2.gml`
2. Click in the `Line Graph` option on toolbar
3. Click in the `Inverse Line Graph` option on toolbar

#### After debbuging, i got the following traceback:
```
C:\Users\Fernando Pimenta\Documents\Github\GraphFilter\venv\lib\site-packages\netgraph\_utils.py:360: RuntimeWarning: invalid value encountered in divide
  v = v / np.linalg.norm(v, axis=-1)[:, None] # unit vector
Traceback (most recent call last):
  File "C:\Users\Fernando Pimenta\Documents\Github\GraphFilter\source\controller\project_controller.py", line 340, in on_operations_button
    calculate(project_information_store.current_graph)
  File "C:\Users\Fernando Pimenta\Documents\Github\GraphFilter\source\store\operations_graph.py", line 30, in calculate
    return nx.inverse_line_graph(graph)
  File "C:\Users\Fernando Pimenta\Documents\Github\GraphFilter\venv\lib\site-packages\networkx\utils\decorators.py", line 766, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 14", line 5, in argmap_inverse_line_graph_10
  File "C:\Users\Fernando Pimenta\Documents\Github\GraphFilter\venv\lib\site-packages\networkx\generators\line.py", line 290, in inverse_line_graph
    P = _find_partition(G, starting_cell)
  File "C:\Users\Fernando Pimenta\Documents\Github\GraphFilter\venv\lib\site-packages\networkx\generators\line.py", line 388, in _find_partition
    u = partitioned_vertices.pop()
IndexError: pop from empty list
```

I believe that to solve this problem, it's enough to use a generic Exception clause in the method that calculates the operation.

**Comment by atilaajones** [comment]
Your previous solution may well work, because there is an inverse line in the graph.
