### ISSUE TITLE
Missing PDF files after exporting all the graphs as PDFs.

### ISSUE THREAD

**Issue by lichengzhang1** [GraphFilter/GraphFilter#427]
Congratulations on the release of your new software, Graph Filter v3.6.8! However, I have noticed an issue. When I try to export all the graphs to PDFs, I cannot find the resulting PDF files. Other formats such as TikZ and PNG are fine, so I'm wondering if I'm missing something.

I use Windows 10.

Best wishes,
Licheng.

**Comment by LBeghini** [comment]
Thank you very much for promptly reporting us this bug. We are already investigating what might have happened.

**Comment by LBeghini** [comment]
What happens when trying to export the files to PDF, is that the following error is thrown:

```
qt.qpa.fonts: Populating font family aliases took 89 ms. Replace uses of missing font family "Cambria Math" with one that exists to avoid this cost.
netgraph/_utils.py:360: RuntimeWarning: invalid value encountered in divide
QMainWindow::saveState(): 'objectName' not set for QDockWidget 0x600002af41c0 'Files;
QMainWindow::saveState(): 'objectName' not set for QToolBar 0x600002af04d0 ''
Traceback (most recent call last):
  File "source/controller/project_controller.py", line 349, in on_export_button
  File "source/store/export_graph_to.py", line 107, in export
  File "matplotlib/pyplot.py", line 954, in savefig
  File "matplotlib/figure.py", line 3274, in savefig
  File "matplotlib/backends/backend_qtagg.py", line 81, in print_figure
  File "matplotlib/backend_bases.py", line 2285, in print_figure
  File "contextlib.py", line 135, in __enter__
  File "matplotlib/backend_bases.py", line 2188, in _switch_canvas_and_return_print_method
  File "matplotlib/backend_bases.py", line 146, in get_registered_canvas_class
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'matplotlib.backends.backend_pdf'
```

This error was already reported here https://github.com/Nuitka/Nuitka/issues/827.
